name : this is github action
run-name: this is the run name
on: [push]
jobs: 
    Echo: 
        runs-on: ubuntu-latest
        steps:
            - name: cat temp.txt
              run: cat temp.txt
